apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mco-layered-rebuild
  namespace: okd
spec:
  params:
    - name: initial-image
      type: string
      description: Initial image to import
      default: quay.io/vrutkovs/okd-release:4.12.0-0.okd-centos9-full-rebuild
    - name: result-mirror-location
      type: string
      description: Location to mirror resulting images
      default: quay.io/vrutkovs/okd-release
    - name: result-image
      type: string
      description: Resulting release location
      default: quay.io/vrutkovs/okd-release:4.12.0-0.okd-centos9-rebuild
    - name: result-image-name
      type: string
      description: Internal release name
      default: 4.12.0-0.okd-centos9-full-rebuild
  workspaces:
    - name: push-credentials
  tasks:
    - name: initial-import
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc adm release mirror \
              $(params.initial-image) \
              --to-image-stream release
    - name: prepare-build-images
      runAfter:
      - initial-import
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build builder -w && \
            oc start-build forked-dockerfiles -w && \
            oc start-build base -w
    - name: mco
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build machine-config-operator -w
    - name: kubelet
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build hyperkube-rpms -w
    - name: machine-os-content
      runAfter:
      - mco
      - kubelet
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build machine-os-content -w
    - name: new-release
      runAfter:
      - machine-os-content
      taskRef:
        name: new-release
      timeout: "2h0m0s"
      params:
        - name: release-mirror-location
          value: $(params.result-mirror-location)
        - name: release-image
          value: $(params.result-image)
        - name: release-image-name
          value: $(params.result-image-name)
      workspaces:
      - name: credentials
        workspace: push-credentials
