apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: openshift-api-bump
spec:
  params:
    - name: initial-image
      type: string
      description: Initial image to import
      default: registry.ci.openshift.org/origin/release:4.12
    - name: result-mirror-location
      type: string
      description: Location to mirror resulting images
      default: quay.io/vrutkovs/okd-release
    - name: result-image
      type: string
      description: Resulting release location
      default: quay.io/vrutkovs/okd-release:4.12.0-0.okd-openshift-api-bump
    - name: result-image-name
      type: string
      description: Internal release name
      default: 4.12.0-0.okd-openshift-api-bump
  workspaces:
    - name: push-credentials
  tasks:
    - name: initial-import
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc adm release mirror \
              $(params.initial-image) \
              --to-image-stream release
    - name: prepare-build-images
      runAfter:
      - initial-import
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build builder -w && \
            oc start-build forked-dockerfiles -w && \
            oc start-build base -w
    - name: cluster-etcd-operator
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build cluster-etcd-operator -w
    - name: cluster-machine-approver
      runAfter:
      - prepare-build-images
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc start-build cluster-machine-approver -w
    - name: new-release
      runAfter:
      - cluster-etcd-operator
      - cluster-machine-approver
      taskRef:
        name: new-release
      timeout: "2h0m0s"
      params:
        - name: release-mirror-location
          value: $(params.result-mirror-location)
        - name: release-image
          value: $(params.result-image)
        - name: release-image-name
          value: $(params.result-image-name)
      workspaces:
      - name: credentials
        workspace: push-credentials
