apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: release
  namespace: okd
spec:
  lookupPolicy:
    local: true
  tags:
    - name: fedora-coreos
      from:
        kind: DockerImage
        name: quay.io/coreos-assembler/fcos:next-devel
      referencePolicy:
        type: Source
    - name: kuryr-cni
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9-minimal:9.0.0
      referencePolicy:
        type: Source
    - name: kuryr-controller
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9-minimal:9.0.0
      referencePolicy:
        type: Source
