apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: forked-dockerfiles
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/vrutkovs/okd-centos9-rebuild'
      ref: openshift-api-bump
    contextDir: forks
    images: []
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: 'release:forked-dockerfiles'
