apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-monitoring-operator
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/vrutkovs/cluster-monitoring-operator'
      ref: 4.12-no-proms
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-monitoring-operator'
