apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: cluster-machine-approver
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/cluster-machine-approver'
      ref: release-4.12
    contextDir: .
    images:
      - from:
          kind: ImageStreamTag
          name: 'release:forked-dockerfiles'
        paths:
          - sourcePath: /code/cluster-machine-approver/Dockerfile.centos9
            destinationDir: "."
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile.rhel
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:cluster-machine-approver'
